<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class BrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        Brand::factory()->count(10)->create();

        DB::table('brands')->insert([
            [
                'name' => 'Wolsley',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'De Dion Bouton',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Norddeutsh',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Brasier',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Star Company',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Argylls',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'UNIC',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Albion',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FIAT',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GMC',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Willys',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa Metalúrgica Lda',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chevrolet',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Republic',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruggles',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Stewart',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Manchester',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Daimler-Benz',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ford',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mercedes Benz',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dover',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'REO',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rugby',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bedford',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Buddy Stewart',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dodge',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Diamond',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Federal',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'International',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Studebaker',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fargo',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Volvo',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'MAN',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seddon',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Morris',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Commer',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Austin',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Guy',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Panhard',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Fargo',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Borgward',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Leyland',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Fordson',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'AEC',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Scania',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'OM',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'name' => 'Toyota',
                'short' => null,
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
