<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class CompaniesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        Company::factory()->count(10)->create();

        DB::table('companies')->insert([
            [
                'name' => 'Auto Transportadora do Porto Santo, Lda',
                'short' => 'ATPS',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cooperativa de Automóveis da Levada de Santa Luzia, Lda',
                'short' => 'CALSLL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Companhia dos Automóveis de Santo António, Lda',
                'short' => 'CASAL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Companhia de Automóveis de Santa Luzia, Lda',
                'short' => 'CASLL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Companhia de Automóveis de Turismo, Lda',
                'short' => 'CAT',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Companhia dos Carros de São Gonçalo, Lda',
                'short' => 'CCSG',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Companhia dos Carros de São Gonçalo S.A',
                'short' => 'CCSG S.A',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Câmara Municipal do Funchal',
                'short' => 'CMF',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa de Automóveis do Caniço, Lda',
                'short' => 'EACL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empreza de Automóveis de Câmara de Lobos, Lda',
                'short' => 'EACLL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa Automobilística do Leste da Madeira, Lda',
                'short' => 'EALML',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa Automobilista da Ribeira Brava, Lda',
                'short' => 'EARBL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa de Automóveis de Santo António, Lda',
                'short' => 'EASAL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa de Automóveis de São Gonçalo, Lda',
                'short' => 'EASGL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa Automobilística de São Martinho, Lda',
                'short' => 'EASML',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empresa Camachense de Automóveis, Lda. / Emílio de Castro e Companhia Lda',
                'short' => 'ECAL / ECCL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empreza Progresso de Automóveis Funchalense, Lda',
                'short' => 'EPAFL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Empreza Transportes Rápidos da Ajuda, Lda',
                'short' => 'ETRAL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Horários do Funchal, Lda',
                'short' => 'HF',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Instituto Apoio Social das Forças Armadas, Porto Santo',
                'short' => 'IASFA',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade Automobilistica de Câmara de Lobos, Lda',
                'short' => 'SACLL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade de Automóveis do Estreito de Câmara de Lobos, Lda',
                'short' => 'SAECLL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade de Automóveis da Madeira, Lda',
                'short' => 'SAM',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade de Automóveis de São Roque, Lda',
                'short' => 'SASRL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade de Automóveis de São Roque do Faial, Lda',
                'short' => 'SASRFL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sociedade União de Santo António, Lda',
                'short' => 'SUSAL',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Transfunchal, Lda',
                'short' => 'TF',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Henry Harvey Foster',
                'short' => 'HHF',
                'owner' => null,
                'begin_year' => null,
                'state_id' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
